sudo: false
language: java
jdk: oraclejdk8

notifications:
  email: false
env:
  global: TERM=dumb

install: gradle setupCIWorkspace
script: gradle build

cache:
  directories:
  - $HOME/.gradle/caches
